- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present

- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes

- name: Debian python-pip is present
  apt:
    name: python-pip
    state: present
    force: yes

- name: Debian docker-py is present
  pip:
    name: docker-py
    state: latest

- name: Debian files are present
  template:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_result

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed and is_systemd is defined

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed

- name: Docker config directory for root is present
  file: path=/root/.docker state=directory owner=root group=root mode=0755

- name: Docker credentials for consort registry for root are present
  template:
    src: "config.json"
    dest: "/root/.docker/config.json"

- name: Docker config directory for vagrant is present
  file: path=/home/vagrant/.docker state=directory owner=vagrant group=vagrant mode=0755

- name: Docker credentials for consort registry for root are present
  template:
    src: "config.json"
    dest: "/home/vagrant/.docker/config.json"
