- name: pull latest DockerUI image
  docker_image:
    name: uifd/ui-for-docker:latest
    force: yes

- name: DockerUI is running
  docker:
    image: uifd/ui-for-docker:latest
    labels:
      category: base
    name: dockerui
    ports: 9000:9000
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
